### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by eromoe** [tcrossland/spacy-annotator#1]
OS: windows 10 x64
nodejs : v6.9.5

Firefox and Chrome both get `Uncaught ReferenceError: process is not defined`.

I found the error happen at:
```
/**
 * Run the matchers when in browser.
 */

if (process.browser) {    //  this line got error
  var userAgent = window.navigator.userAgent;
  var _iteratorNormalCompletion = true;
  var _didIteratorError = false;
  var _iteratorError = undefined;
```

**Comment by tcrossland** [comment]
The [line](https://github.com/ianstormtaylor/slate/blob/master/src/constants/environment.js#L46) that's failing is from the [slate](https://github.com/ianstormtaylor/slate) editor which the annotator app uses.

Unfortunately I haven't been able to reproduce the issue (I don't have a Windows machine). How are you running the app?

**Comment by eromoe** [comment]
1. git clone
2. npm install -g brunch
3. cd spacy-annotator
4. npm install
5. brunch watch --server

That piece of code looks like use just for frontend.

**Comment by tcrossland** [comment]
Could try adding a global in the `brunch-config.js`? Like this:

```javascript
exports.config = {
  files: {
    javascripts: { joinTo: 'app.js' },
    stylesheets: { joinTo: 'app.css' }
  },

  plugins: {
    babel: { presets: ['es2015', 'react'] }
  },

  npm: {
    enabled: true,
    styles: {
      bootstrap: ['dist/css/bootstrap.css']
    },
    globals: {
      process: 'process'
    }
  }
};
```

**Comment by tcrossland** [comment]
I've opened an [issue](https://github.com/ianstormtaylor/slate/issues/609) on the slate repository. Will leave this open until you confirm that the workaround works or the slate issue is resolved.

**Comment by eromoe** [comment]
It works ! Thank you very much.
