### ISSUE TITLE
Blank browser page after http service is started.

### ISSUE THREAD

**Issue by geledek** [tcrossland/spacy-annotator#2]
Hi, 
On MacOS 10.12.4, I was able to compile and build up to `brunch watch --server `.

Console output:
> -> % brunch watch --server
>10:25:04 - info: application started on http://localhost:3333/
>10:25:06 - info: compiling
>10:25:10 - info: compiling.
>10:25:16 - info: compiling..
>10:25:20 - info: compiling...
>10:25:24 - info: compiling
>10:25:26 - info: compiled 735 files into 2 files, copied 6 in 24.4 sec

But browsing http://localhost:3333/ shows nothing but only the title 'Spacy Annotator'.

Did I miss anything?

**Comment by tcrossland** [comment]
Could you check if any error appears in the Javascript Console?

**Comment by geledek** [comment]
@tcrossland yes, there is an error.

> app.js:61 Uncaught Error: Cannot find module 'redux-saga/effects' from 'sagas/entities.js'
> at require (app.js:61)
> at expanded (app.js:34)
>    at entities.js:11
>    at initModule (app.js:42)
>    at require (app.js:59)
>    at expanded (app.js:34)
 >   at index.js:8
  >  at initModule (app.js:42)
   > at require (app.js:59)
   > at expanded (app.js:34)

**Comment by geledek** [comment]
@tcrossland Any idea what caused the error?

**Comment by tcrossland** [comment]
Ok, this seems to be a problem with a dependency which has changed (https://github.com/redux-saga/redux-saga). As a workaround I've fixed the version of redux-saga for the time being.

**Comment by tcrossland** [comment]
It seems that the brunch build system has an issue with nested modules:

https://github.com/brunch/brunch/issues/1695

**Comment by tcrossland** [comment]
As a slightly tidier workaround I've created an alias in brunch's configuration file.

https://github.com/tcrossland/spacy-annotator/commit/56fca1ac0721f20f439b8686aecab541479e8fc9#diff-cf6d64b6ab9de528b5d0ed6c5db05f3a
